-- MySQL Script generated by MySQL Workbench
-- Tue Sep 12 23:54:34 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema p2p
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `p2p` ;

-- -----------------------------------------------------
-- Schema p2p
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p2p` DEFAULT CHARACTER SET utf8 ;
USE `p2p` ;

-- -----------------------------------------------------
-- Table `p2p`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p2p`.`user` ;

CREATE TABLE IF NOT EXISTS `p2p`.`user` (
  `phone` VARCHAR(20) NOT NULL,
  `idCard` VARCHAR(30) NOT NULL,
  `stdNo` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `school` VARCHAR(30) NOT NULL,
  `major` VARCHAR(50) NOT NULL,
  `grade` INT NOT NULL DEFAULT 1,
  `gpa` VARCHAR(20) NOT NULL DEFAULT 0,
  `home` VARCHAR(100) NOT NULL,
  `motherName` VARCHAR(30) NOT NULL,
  `motherIncome` INT NOT NULL DEFAULT 0,
  `motherJob` VARCHAR(30) NOT NULL,
  `fatherName` VARCHAR(30) NOT NULL,
  `fatherIncome` INT NOT NULL DEFAULT 0,
  `fatherJob` VARCHAR(30) NULL,
  `zhiMaCredit` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`phone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p2p`.`user` ;

CREATE TABLE IF NOT EXISTS `p2p`.`user` (
  `phone` VARCHAR(20) NOT NULL,
  `idCard` VARCHAR(30) NOT NULL,
  `stdNo` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `school` VARCHAR(30) NOT NULL,
  `major` VARCHAR(50) NOT NULL,
  `grade` INT NOT NULL DEFAULT 1,
  `gpa` VARCHAR(20) NOT NULL DEFAULT 0,
  `home` VARCHAR(100) NOT NULL,
  `motherName` VARCHAR(30) NOT NULL,
  `motherIncome` INT NOT NULL DEFAULT 0,
  `motherJob` VARCHAR(30) NOT NULL,
  `fatherName` VARCHAR(30) NOT NULL,
  `fatherIncome` INT NOT NULL DEFAULT 0,
  `fatherJob` VARCHAR(30) NULL,
  `zhiMaCredit` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`phone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`volunteer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p2p`.`volunteer` ;

CREATE TABLE IF NOT EXISTS `p2p`.`volunteer` (
  `volunteerID` INT NOT NULL AUTO_INCREMENT,
  `stdNo` VARCHAR(30) NOT NULL,
  `starttime` DATE NOT NULL,
  `duration` INT NOT NULL,
  `activity` VARCHAR(50) NOT NULL,
  `volunteercol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`volunteerID`, `stdNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`bankCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p2p`.`bankCard` ;

CREATE TABLE IF NOT EXISTS `p2p`.`bankCard` (
  `phone` VARCHAR(20) NOT NULL,
  `bankCard` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`phone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`scholarship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p2p`.`scholarship` ;

CREATE TABLE IF NOT EXISTS `p2p`.`scholarship` (
  `scholarID` INT NOT NULL AUTO_INCREMENT,
  `stdNo` VARCHAR(30) NOT NULL,
  `scholarTime` DATE NOT NULL,
  `money` INT NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`scholarID`, `stdNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`punishment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p2p`.`punishment` ;

CREATE TABLE IF NOT EXISTS `p2p`.`punishment` (
  `stdNo` VARCHAR(30) NOT NULL,
  `punishmentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`stdNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`progross`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p2p`.`progross` ;

CREATE TABLE IF NOT EXISTS `p2p`.`progross` (
  `phone` VARCHAR(20) NOT NULL,
  `hasBasicAuth` INT NOT NULL DEFAULT 0,
  `hasSchoolAuth` INT NOT NULL DEFAULT 0,
  `hasBankAuth` INT NOT NULL DEFAULT 0,
  `hasZhiMaAuth` INT NOT NULL DEFAULT 0,
  `hasAllAuth` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`phone`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
