-- MySQL Script generated by MySQL Workbench
-- Tue Sep 12 23:33:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `phone` VARCHAR(20) NOT NULL,
  `idCard` VARCHAR(30) NOT NULL,
  `stdNo` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `school` VARCHAR(30) NOT NULL,
  `major` VARCHAR(50) NOT NULL,
  `grade` INT NOT NULL DEFAULT 1,
  `gpa` VARCHAR(20) NOT NULL DEFAULT 0,
  `home` VARCHAR(100) NOT NULL,
  `motherName` VARCHAR(30) NOT NULL,
  `motherIncome` INT NOT NULL DEFAULT 0,
  `motherJob` VARCHAR(30) NOT NULL,
  `fatherName` VARCHAR(30) NOT NULL,
  `fatherIncome` INT NOT NULL DEFAULT 0,
  `fatherJob` VARCHAR(30) NULL,
  `zhiMaCredit` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`phone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`volunteer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`volunteer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`volunteer` (
  `stdNo` VARCHAR(30) NOT NULL,
  `volunteerID` INT NOT NULL AUTO_INCREMENT,
  `starttime` DATE NOT NULL,
  `duration` INT NOT NULL,
  `activity` VARCHAR(50) NOT NULL,
  `volunteercol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`volunteerID`, `stdNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consumeRecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`consumeRecord` ;

CREATE TABLE IF NOT EXISTS `mydb`.`consumeRecord` (
  `bankCard` VARCHAR(30) NOT NULL,
  `recordid` INT NOT NULL,
  `consumeTime` DATE NOT NULL,
  `money` FLOAT NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`bankCard`, `recordid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bankCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bankCard` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bankCard` (
  `phone` VARCHAR(20) NOT NULL,
  `bankCard` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`phone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`scholarship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`scholarship` ;

CREATE TABLE IF NOT EXISTS `mydb`.`scholarship` (
  `stdNo` VARCHAR(30) NOT NULL,
  `scholarID` INT NOT NULL AUTO_INCREMENT,
  `scholarTime` DATE NOT NULL,
  `money` INT NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`stdNo`, `scholarID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`punishment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`punishment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`punishment` (
  `stdNo` VARCHAR(30) NOT NULL,
  `punishmentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`stdNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`progross`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`progross` ;

CREATE TABLE IF NOT EXISTS `mydb`.`progross` (
  `phone` VARCHAR(20) NOT NULL,
  `hasBasicAuth` INT NOT NULL DEFAULT 0,
  `hasSchoolAuth` INT NOT NULL DEFAULT 0,
  `hasBankAuth` INT NOT NULL DEFAULT 0,
  `hasZhiMaAuth` INT NOT NULL DEFAULT 0,
  `hasAllAuth` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`phone`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
